BEGIN TRY 
BEGIN TRANSACTION;
UPDATE day5.Accounts
SET Balance = Balance - 200
WHERE AccountID =1;
UPDATE day5.Accounts
SET Balance = Balance + 200
WHERE AccountID = 2;
  COMMIT TRANSACTION;
END TRY
BEGIN  CATCH
ROLLBACK TRANSACTION;
PRINT'TRANSACTON FAILED AND WAS ROLLED BACK.';
END CATCH;